Task1
evgenum/Scala-complete-course pull request #1
Opened 2017-09-22 13:21 UTC by evgenum

Complete task1. Request to merge

2017-09-25 20:11 UTC, vatt2001 requested changes

2017-09-25 20:11 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +  * строк метод contains
У тебя split будет выполняться столько же раз, сколько будет вызываться возвращаемая функция. Хотя можно количество split-ов сократить до одного.

2017-10-03 10:21 UTC, evgenum commented
Fix the functional computation. Request to merge.

2017-10-04 18:23 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Computations.scala
> +    dataArray => filterData.split(" ").filter(dataItem =>dataArray.contains(dataItem))
эта реализация не соответствует описанию.
каждый вызов filterApplied(dataArray) будет сначала разбивать массив и потом фильтровать
массив можно разбить один раз при создании  функции в functionalComputation(filterData)

2017-10-04 19:05 UTC, merged