Task3
evgenum/Scala-complete-course pull request #3
Opened 2017-10-18 11:18 UTC by evgenum

Complete Task3. Request to merge

2017-10-19 22:29 UTC, vatt2001 commented
Не нашел здесь задачи на коллекции

2017-10-19 22:29 UTC, vatt2001 requested changes

2017-10-19 22:29 UTC, vatt2001 commented on src/test/scala/lectures/functions/FibonacciTest.scala
> +    fibs(7) should be (13)
Один тест должен проверять только один сценарий. При объединении нескольких сценариев в один тест усложняется поиск причины падения.

2017-11-02 23:23 UTC, vatt2001 requested changes

2017-11-02 23:23 UTC, vatt2001 commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +    }
Везде, где надо сравнивать с null, хорошо подходит обернуть в `Option()`. Там null автоматически становится `None`

2017-11-02 23:23 UTC, vatt2001 commented on src/main/scala/lectures/functions/Authentication.scala
> +    if( authByCard.isDefinedAt(user)) authByCard.lift(user)
Зачем тебе isDefinedAt, если lift уже сам это делает?
Комозицию методов можно сделать через orElse

2017-11-02 23:23 UTC, vatt2001 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +      case it => it.junk.contains(Knife)
Так, как ты написал, match вообще здесь не нужен

2017-12-06 08:57 UTC, sergeypopov83 commented on src/main/scala/lectures/matching/SortingStuff.scala
> -    def findMyKnife(stuffBox: StuffBox): Boolean = stuffBox match {
f1 и f2, ниже по коду, лишние

2017-12-06 08:57 UTC, merged