Task10
evgenum/Scala-complete-course pull request #8
Opened 2018-05-07 11:30 UTC by evgenum

2018-05-16 18:11 UTC, vatt2001 requested changes

2018-05-16 18:11 UTC, vatt2001 commented on src/main/scala/lectures/eval/LazyScheduler.scala
> +        def apply(n: Int) = if( c.instant().isBefore(i)) v.apply(n) else throw new Exception("View is expired.")
По условию задачи надо не бросать кастомное исключение, а вести себя как будто коллекция пуста

2018-05-16 18:11 UTC, vatt2001 commented on src/main/scala/lectures/eval/LazyScheduler.scala
> +        def apply(n: Int) = if( c.instant().isBefore(i)) v.apply(n) else throw new Exception("View is expired.")
Не везде расставлены override, пробелы возле скобок в разных местах стоят по-разному (где-то до, где-то после открывающей скобки)

2018-05-16 18:11 UTC, vatt2001 commented on src/main/scala/lectures/eval/LazyScheduler.scala
> +      class ViewWithExpiration(val e: Instant, val s: Seq[A]) extends SeqView[A, Seq[_]] {
Если это именованный класс, то его лучше объявлять не внутри метода, иначе каждый раз у тебя будет объявляться новый класс "типа с одним и тем же именем".

2018-05-16 18:11 UTC, vatt2001 commented on src/main/scala/lectures/eval/LazyScheduler.scala
> +        def apply(n: Int) = if( c.instant().isBefore(i)) v.apply(n) else throw new Exception("View is expired.")
Копипаста детектед. Проверку времени имеет смысл вынести в отдельный метод.

2018-05-16 18:11 UTC, vatt2001 commented on src/main/scala/lectures/oop/types/package.scala
> +  implicit class OrderingSyntax[T](t: T)(implicit ordering: Ordering[T]) {
Если у тебя натуральный (естественный для данного типа) порядок, то лучше использовать трейт Ordered, у него уже есть эти методы.

2018-05-16 19:40 UTC, evgenum commented on src/main/scala/lectures/oop/types/package.scala
> +  implicit class OrderingSyntax[T](t: T)(implicit ordering: Ordering[T]) {
Если заменить Imlicit context bound на Ordered, то  возможность использовать знаки < > пропадают.

2018-05-17 21:30 UTC, vatt2001 approved these changes

2018-05-17 21:30 UTC, vatt2001 commented on src/main/scala/lectures/oop/types/package.scala
> +  implicit class OrderingSyntax[T](t: T)(implicit ordering: Ordering[T]) {
Согласен, с Ordered это не сработает. Зато для Ordering можно добавить имплисит:
`import scala.math.Ordering.Implicits._`
И тогда всё зарабоает.

2018-05-17 21:30 UTC, merged